version: "1.0"
stages:
  - prepare
  - apply
steps:
  main_clone:
    title: Cloning repository
    type: git-clone
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"
    stage: prepare
  init:
    image: hashicorp/terraform:0.14.7
    title: Initializing Terraform
    stage: apply
    commands:
      - terraform init
      - terraform plan
  apply:
    image: hashicorp/terraform:0.14.7
    title: Applying Terraform
    stage: apply
    commands:
      -  terraform apply -auto-approve 
      - export CLUSTER_NAME=$(terraform output -raw cluster_name)
      - export REGION=$(terraform output -raw region)
      - export DESTROY=$(terraform output -raw destroy)
      - cf_export CLUSTER_NAME REGION DESTROY
    when:
      branch:
        only:
          - master
